name: user_crud
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
dependencies: 
  cli_dialog: ^0.5.0
  dart_console : ^1.0.0
  executor: ^2.2.2
